### ISSUE TITLE
onCanvasClick dosnt work on first row

### ISSUE THREAD

**Issue by KamilKmitaLasoft** [namespace-ee/react-calendar-timeline#105]
My problem is with onCanvasClick , when try click on first row it dosnt work . Such problem with onCanvasDoubleClick - when double click , return with wrong group . Examply when double on second row function return group from first row .

**Comment by mariusandra** [comment]
Hey! Could you provide some additional information to help debug this?

On the [demo](http://namespace.ee/react-calendar-timeline-docs/) it works fine.

I crated a [webpackbin](https://www.webpackbin.com/bins/-Kmp5BRA25HDJy1SoW47) for you to play with. Can you duplicate the bug there?

**Comment by signalwerk** [comment]
`<notrelated>`

@mariusandra nice idea with the webpackbin. I just stole it for my last two PR :)

`</notrelated>`

**Comment by kmueller** [comment]
Hi, first of all: I like your component very much! Thank you for that!!!
 
You can reproduce the error in webpackbin, when you choose the lineHeight=60:
     <Timeline groups={groups}
                items={items}
                keys={keys}
                fixedHeader='fixed'
                fullUpdate
                lineHeight={60}

In my opinion you could fix this in Timeline.js in the function rowAndTimeFromEvent:
ADAPT LINE:    const { lineHeight, dragSnap, headerLabelGroupHeight, headerLabelHeight } = this.props
...
WRONG!?    //const row = Math.floor((y - (lineHeight * 2)) / lineHeight)
RIGHT!?	const row = Math.floor((y - headerLabelGroupHeight - headerLabelHeight) / lineHeight)

Please check ! To do this you also have to adapt the generate-fake-data.js -> Arrays should always start with index = 0 
...
    groups.push({
WRONG:      id: `${i + 1}`,
RIGHT: id:`${i}`,    // Otherwise the wrong row is returned to callback function!
...
and:
...
    items.push({
      id: i + '',
WRONG:      group: faker.random.number({ min: 1, max: groups.length }) + '',
RIGHT: group: faker.random.number({ min: 0, max: groups.length-1 }) + '',

BR Kai

**Comment by mariusandra** [comment]
Hey, I fixed the first row bug (thanks! your solution worked!) with #118, but then discovered this additional bug: https://youtu.be/2ZqcPwoNtMo . I'm working on a solution for it now and will then release a new version.

**Comment by mariusandra** [comment]
Hey, `v0.14.8` is released with the fixes! Please let me know if it works now.

**Comment by signalwerk** [comment]
@kmueller thank you for your contribution! Just saying; Sometimes it's nice to be listed as contributor in a project for the CV or just for fun. If you send us a pull request in the future we are more than happy to merge it. Since you basically fixed the problem it's nice to see in a `git blame` your name. If you need any help how to do a pull request feel free to ask. but again: thank you! and of course we can also do the corrections with such excellent descriptions!

**Comment by signalwerk** [comment]
@mariusandra thank you for all your work! you are crazy active last couple weeks. niiicee!!

**Comment by mariusandra** [comment]
@kmueller I completely echo @signalwerk 's comments. The fix you sent worked, but since you didn't submit a PR, your name will unfortunately not appear on the [contributors page](https://github.com/namespace-ee/react-calendar-timeline/graphs/contributors). Please feel free to send a PR the next time or ask if there's anything we can help with.

@signalwerk Thanks! :) Perhaps it's also time to think about writing some contributor guidelines? ... that explain, among other things, how to get the development environment set up and how to submit PRs?

**Comment by kmueller** [comment]
@mariusandra @signalwerk Thanks guys, very nice feedback from you, but don't worry about my contribution - very little in comparison to yours. Have a nice day!

**Comment by kmueller** [comment]
I have checked out v0.14.8 - it works !
