### ISSUE TITLE
Does not build with create-react-app

### ISSUE THREAD

**Issue by marwej** [namespace-ee/react-calendar-timeline#134]
I use react-calendar-timeline together with [create-react-app](https://github.com/facebookincubator/create-react-app) but 0.15.0 don't build:

```
./~/react-calendar-timeline/src/lib/Timeline.js
Module parse failed: .../node_modules/react-calendar-timeline/src/lib/Timeline.js Unexpected token (73:19)
You may need an appropriate loader to handle this file type.
| 
| export default class ReactCalendarTimeline extends Component {
|   static propTypes = {
|     groups: PropTypes.oneOfType([PropTypes.array, PropTypes.object]).isRequired,
|     items: PropTypes.oneOfType([PropTypes.array, PropTypes.object]).isRequired,
```

I don't want to eject my projects to include more loaders in the build process which makes it impossible to use this version.

(Thanks for a great product, by the way!)

**Comment by mariusandra** [comment]
Hi, the problem is closely connected to [this point](https://github.com/namespace-ee/react-calendar-timeline#im-using-babel-with-rollup-or-webpack-2-and-im-getting-strange-bugs-with-click-events) in the readme. 

The issue is that your app need to have [babel-plugin-transform-class-properties](https://babeljs.io/docs/plugins/transform-class-properties/) enabled. While we ship transpiled ES5 code with the module, webpack 2+ uses the original ESnext code by default, which needs this plugin.

So there are two options: use the transpiled code or install the plugin.

1) To use the transpiled code, simply switch your `include` statement to this:

```js
// import Timeline from 'react-calendar-timeline' // old
import Timeline from 'react-calendar-timeline/lib/lib/Timeline' // new
```

This path may change in the future, so pay attention to the [changelog](https://github.com/namespace-ee/react-calendar-timeline/blob/master/CHANGELOG.md) when upgrading!

2) Install the babel plugin... or at least all stage-2 plugins (or even stage-0). It's probably easiest to install [custom-react-scripts](https://github.com/kitze/custom-react-scripts)

```bash
yarn add custom-react-scripts
yarn remove react-scripts
```

Then add this line to a file called `.env`:

```
REACT_APP_BABEL_STAGE_0=true
```

Then you may import the component like you would normally

```js
import Timeline from 'react-calendar-timeline'
```

**Comment by p-glynn** [comment]
Using custom-react-scripts worked great for me when i was running into this same issue using webpack 2+. Thanks so much!!

**Comment by DChefHarshil** [comment]
@mariusandra I have similar but little bit different issue. I am using create-react-app for building the app. The app works fine in development mode but when I run the production build using `serve -s build`, I can't see anything on timeline but headers and sidebar. I can't even scroll or see any items. This is how it looks. 

![image](https://user-images.githubusercontent.com/58196540/202386049-0ba67aad-6356-40aa-a298-2a75116a3071.png)
