### ISSUE TITLE
Highlight and scroll to an item

### ISSUE THREAD

**Issue by pedro-walter** [namespace-ee/react-calendar-timeline#177]
Hi,

First of all, thanks for your work, I'm using it on a project and my customer is very satisfied with it.

I'm working on a feature where I will need to focus on a pair of items on the same group. I wonder if there's a way to scroll the page to it if it's not visible (might be a group near the end, for example). 

If it's not possible (or too difficult), the alternative would be to create a filter where only the groups I want are displayed.

Thanks in advance!

**Comment by mcMickJuice** [comment]
How are you selecting the item that you want to focus? Is it outside of the timeline (like in a dropdown)?  Also, by "focus", do you mean to say that the timeline scrolls to a date range that shows the items you'd like to display?

If so, you can pass in `visibleTimeStart` and `visibleTimeEnd` from the component that manages the Timeline.  This will update the timeline to "scroll" to this range.  You could determine the start and end based on the min and max dates on your items.

**Comment by pedro-walter** [comment]
Filtering to the date is the easy part. The hard one is when you have, say, 30 groups, and need to focus on one of the bottom ones. That would need either to filter that group to appear at the top, or to scroll the calendar to the bottom groups. I don't like the idea of changing the order of the groups, but if it's my best option, I'll do it.

**Comment by mcMickJuice** [comment]
How about changing what items are passed in to the timeline? So that you're only passing in the item(s) you wanna focus on?  Or is that too disruptive?

**Comment by pedro-walter** [comment]
Depending on the settings, the same group should not have two items in the same timeframe (say a person can't have two appointments in the same time). I think is disruptive, and then the option of putting the said group first is more appealing. Or maybe figure out a way to scroll the page, not sure which approach I'll follow.

**Comment by pedro-walter** [comment]
[This stackoverflow answer](https://stackoverflow.com/a/11986374/2232455) pointed me in the right direction:

`
const item = {
  id: 1,
  group: 2,
  itemProps: {
    id: 'item-1'
  }
}
`

After giving each item an id that will be visible in the DOM, you can scroll into it using the code on that answer:

`
window.scroll(0,findPos(document.getElementById("item-1")) - 80);
`

You can adjust the "80" constant to your liking, but I'm pleased with this amount.

Would be nice if this itemProps attribute could be passed to groups too, this way you can use this same technique to focus on a specific group instead of an item. But maybe this use case is too narrow to bother.

**Comment by mcMickJuice** [comment]
@pedro-walter thats a nice solution there!  For groups, you can define a custom renderer with [groupRenderer](https://github.com/namespace-ee/react-calendar-timeline#grouprenderer) in which you can specify this id, or really anything you need to get a handle on the html element to scroll to.

Either way, I think this issue is somewhat outside the scope of this component and its features.  If you agree, would you mind closing the issue?

**Comment by pedro-walter** [comment]
Sure, go ahead.

Em 17 de nov de 2017 12:20, "Mike Joyce" <notifications@github.com>
escreveu:

**Comment by mcMickJuice** [comment]
actually...i dont have contributor rights on this repo, but since you opened the issue, you can close it :)

**Comment by madisvain** [comment]
@mcMickJuice I see you have done quite some work on this timeline component and have some pending pull requests. We have not had much time lately to keep up with everything so it would be very good to have you as a contributor with commit access if you'd like to?

@mariusandra pointed it out to me also that this would actually be good in the long run if you have interest and we don't want this component to die out because of inactivity.

Let us know what you think.
