### ISSUE TITLE
Add Columns in Sidebar

### ISSUE THREAD

**Issue by sabina4** [namespace-ee/react-calendar-timeline#185]
Hello,

How can I add columns in sidebar?
I am trying to achieve this functionality:

![prescmeds](https://user-images.githubusercontent.com/6688473/32781865-2e2deabc-c94f-11e7-9718-0638c3a695b3.jpg)

columns with a timeline that expands and collapses 

thanks

**Comment by mcMickJuice** [comment]
Hi @sabina4 , re: the columns in sidebar, take a look at the readme as it pertains to:
[sidebarContent prop](https://github.com/namespace-ee/react-calendar-timeline#sidebarcontent) - component that allows you to control whats rendered at top of left sidebar
[groupRenderer prop](https://github.com/namespace-ee/react-calendar-timeline#grouprenderer) - component that allows you to control whats displayed for each item in the left sidebar

**Comment by sabina4** [comment]
@mcMickJuice i tried the groupRenderer prop however it doesn't take into consideration the content size for the line height to grow and shrink accordingly.

**Comment by sabina4** [comment]
here is a link that briefly shows the problem

https://codesandbox.io/s/o4pzy4mlz6

**Comment by mcMickJuice** [comment]
I believe this is because the lineHeight is considered static and wont grow/hide based on the content in the jsx returned by groupRenderer prop. You'll need to manage the contents of that group yourself and if you have a ton of content, you can increase the sidebarWidth, either statically or dynamically as it is a prop
