### ISSUE TITLE
Is there a hook for zoom events?

### ISSUE THREAD

**Issue by xiorcal** [namespace-ee/react-calendar-timeline#248]
I need to perform computations on zoom in/out (see #238 for the why ) but I can't find a hook for zoom events.

computation can be done in item renderer but it really impact TL performance because any scroll of the TL triggers it...

**Comment by mcMickJuice** [comment]
No, it doesn't look like there is. what information would you find useful to be included in this callback? Off the top of my head:

- visibleStartDate and endDate
- timelineStartDate and endDate
- primary timeline unit and secondary timeline unit (i.e. what units are showing in the headers)

**Comment by xiorcal** [comment]
I need nothing more than visibleStartDate and endDate but your suggestions sounds good would save some trouble to have units :)

**Comment by mcMickJuice** [comment]
Cool.  I can't promise when I can get to this but if you wanted to give it a shot, you can start with [updateScrollCanvas](https://github.com/namespace-ee/react-calendar-timeline/blob/master/src/lib/Timeline.js#L618) where you can detect if we're changing zoom or not.  Whatever prop you pass in here can then be used.

This is based on like...1 minute of looking at the code so I might be wrong.  I'd like if we could return the [timelineContext](https://github.com/namespace-ee/react-calendar-timeline/blob/master/src/lib/Timeline.js#L295) instead of individual data values.  `timelineContext` can be expanded to include the following:

- width
- visibleStartDate and endDate
- canvasStartDate and endDate
- primary timeline unit and secondary timeline unit (i.e. what units are showing in the headers)

**Comment by mcMickJuice** [comment]
pushed in v0.15.8

**Comment by spyzzz** [comment]
Hello, i'm working with @xiorcal , i've tested the onZoom function, and its fits our needs perfectly.
TYVM.
