### ISSUE TITLE
Feature request: add possibility for tooltip through mouse event

### ISSUE THREAD

**Issue by b5imply** [namespace-ee/react-calendar-timeline#272]
I looked through the code and it could be very simple to add functionality for **custom tooltip**.  This can be achieved with passing down a function to the Item div and return the itemId for starters. It would be very similar to the onItemSelect function, but the difference is that it refers to a mouse hover event instead of click.

This would be nice if someone could look at this. It should be simple to implement, although I can see if this process need to be tested thoroughly first.

Comments is appreciated =)

**Comment by mcMickJuice** [comment]
Hi @b5imply this can be achieved by providing a component to `itemRenderer` prop ([see docs]((https://github.com/namespace-ee/react-calendar-timeline#itemrenderer)).

In fact, it's in the back of my mind to remove the onItem* props and require itemRenderer so that the user can attach the dom events directly to the item.
