### ISSUE TITLE
Timeline crashes if defaultTimeStart/End and visibleTimeStart/End is not provided

### ISSUE THREAD

**Issue by forki** [namespace-ee/react-calendar-timeline#299]
![image](https://user-images.githubusercontent.com/57396/39568498-babc3008-4ec2-11e8-914a-ffd49e768a81.png)

From reading the docs we should just need to specify `start_time` - but then it fails

**Comment by hotyhuang** [comment]
Hi @forki , this is requiring `defaultTimeStart` and `defaultTimeEnd` in component property. If you missed these two, that line will throw error.

**Comment by mcMickJuice** [comment]
@forki if @hotyhuang response doesnt help you, can you please provide a sample of this issue in the form of a codesandbox link? Just fork one of the links in the [examples page](https://github.com/namespace-ee/react-calendar-timeline/tree/master/examples)

**Comment by forki** [comment]
I rebuilt it here: https://codesandbox.io/s/kko4w3kno3

basically if you don't specify keys and not DefaultTimeStart and DefaultTimeEnd then it crashes. While I think it should look at `start_time` and `end_time` in the items.

**Comment by mcMickJuice** [comment]
Couple of thoughts:

* the docs around [defaultTimeStart/End](https://github.com/namespace-ee/react-calendar-timeline#defaulttimestart-and-defaulttimeend) should be better (i.e. more explicit) to point this out (need to provide them or visibleTimeStart/End
* I dont think that the initial time view should be determined by start_time and end_time.  Just seems like the user should be specific here in what their initial view is

I guess the workaround for this is to throw a better error if visibleTimeStart or defaultTime is not provided

**Comment by mcMickJuice** [comment]
More descriptive error message included in #318 .  Removed onTimeInit prop since it serves no purpose anymore.

A few of reasons for this:
* The user should be explicit in the default start or end date of the timeline
* I feel like there would be strange issues that occur if we calculate these default start and end dates based on items (think items that differ in time range by multiple years) and would result in issues that are not bugs.
* This change simplifies the codebase and removes a prop that is IMO useless

**Comment by mcMickJuice** [comment]
Fixed in 0.17.0

**Comment by Ilaiwi** [comment]
revisit after `refactor stackItems`
