### ISSUE TITLE
unix timestamp and offset

### ISSUE THREAD

**Issue by flyalex** [namespace-ee/react-calendar-timeline#31]
Hi!

Still working with your timeline calendar, thank you for that)

Following recommendation in the doc I am passing unix time stamp in milliseconds in to items. Just found that all items on timeline have different times. The difference is +3hrs which is my timezone.

Is there any way to draw items without any time transformation, but just as it is?

Thanx,
Alex

**Comment by ochervak** [comment]
+1

**Comment by flyalex** [comment]
(sorry for delay)

So, when I map items like this: 
`start_time: start_time: el.unixtime_start `
(which is timestamp in milliseconds), I got my items on timeline shifted for a value of my timezone (+3).

As temporary solution to complete demo, I make:
`startTime.add(-startTime.utcOffset(), 'minutes');`
In this case items on timeline are on positions corresponding to timestamp time.

**Comment by mariusandra** [comment]
Hey, I don't have a lot of time to debug it myself, sorry.
However what I feel can help is to replace "moment" with "moment-timezone" and set it up with the right timezone. It could work, but I'm not 100% sure.

Something like

```js
// in the file where you call your first ReactDOM.render()

import moment from 'moment-timezone'

// get timezone and locale from some config 
moment.tz.setDefault(timezone)
moment.locale(locale)
```

Since `moment` is a peerDependency for `react-calendar-timeline`, you could possibly define an alias for `moment` to `moment-timezone` in your `webpack.conf.js`. Something like:

```
    alias: {
      'moment-timezone': path.join(__dirname, 'node_modules', 'moment-timezone')
    }
```

Perhaps it will work without the alias, perhaps with it, or perhaps not at all. In any case, this is what I would try first.
