### ISSUE TITLE
Cannot resize on 'left' edge

### ISSUE THREAD

**Issue by acemac** [namespace-ee/react-calendar-timeline#330]
**Describe the bug**
Using Chrome 66, left edge of item cannot be resized with mouse

**To Reproduce**
1. Go to the resizing and moving example https://codesandbox.io/s/8nl1l4j6rj
2. Click on and item's left edge and try to resize 

**Expected behavior**
The item drags out from the left as it does with the right edge

**Library Version**
0.16.3

**Desktop (please complete the following information):**

* OS: Win Server 2012 R2
* Browser: Chrome
* Version: 66

**Comment by mcMickJuice** [comment]
This is related to how the Timeline is configured in this example:

* the Timeline component accepts a `canResize` prop. Detailed [here](https://github.com/namespace-ee/react-calendar-timeline#canresize)
* the demo had the value of `true` passed to the component. Since the items did not specify their own `canResize`, resize was only allowed on the right

This is confusing and should be updated.  However, any changes related to this interaction will occur after we refactor itemRenderer to be more robust.  See https://github.com/namespace-ee/react-calendar-timeline/pull/308

Anyways, the demo you mention has been updated in the examples section.  [Here's the updated link](https://codesandbox.io/s/ww7wr5k8ww)
