### ISSUE TITLE
Header Dates are incorrect if groups is initially empty

### ISSUE THREAD

**Issue by morulus** [namespace-ee/react-calendar-timeline#356]
If as an initial value for prop `groups` I pass an empty array, then the displayed date does not correspond to the values of `defaultTimeStart` and `defaultTimeEnd`.

This causes problems with lazy loading of groups and when empty groups came from the server

Here is the example. I'm trying to display the year 2018, but 2017 is displayed.
https://codesandbox.io/s/rwz71pp20n

**Comment by mcMickJuice** [comment]
This is a nasty bug to fix so until I can get to it, the workaround is, instead of an empty array, pass in a dummy group, maybe with a title of "fetching groups" or something.  Then your default start/end will be respected and everything will be fine when your actual groups are loaded.

As an FYI, the bug is related to how the Scroll header is affected when you scroll the timeline body.  When you have no groups, you have no timeline body so there is no initial scrollLeft offset reported to the header.

**Comment by morulus** [comment]
Ok, I got it.

**Comment by Ilaiwi** [comment]
released in 0.25.0
