### ISSUE TITLE
CanMove set to False doesn't forbid moving items

### ISSUE THREAD

**Issue by schevall** [namespace-ee/react-calendar-timeline#484]
Great component, exactly what we needed, but it seems that the canMove bool no longer fill its purpose

**Describe the bug**
When canMove is set to False, items can still be moved

**To Reproduce**
On the example given by this repo about restricting resize and move. Set canMove to false for all items

**Expected behavior**
Items with canMove === False are not draggable

**Screenshots**

**Library Version**
"react-calendar-timeline": "0.22.0",

**Desktop (please complete the following information):**

* OS: IOS
* Browser Chrome Version 70.0.3538.110 (Build officiel) (64 bits)

**Comment by Ilaiwi** [comment]
Hello guys. I will include a fix for this in the next release. I would really appreciate it if you guys submit a PR to fix this. it will make it easier for me and the release will go out faster

**Comment by acemac** [comment]
A workaround to this could be to use moveResizeValidator to prevent the moving. and set `canChangeGroup={false}`


This is a problem in `Item.js`. I am not sure why it has not presented sooner. The problem code has been around for a long time.

When items initially selected, their click handlers are mounted in `mountInteract`. 

As permissions for the item can change, the permissions to resize or move are updated on component update in `componentWillReceiveProps`, if the permissions have not changed, the permission will not be changed.

The bug is that the initial set for if a component can be moved does not check `props.canMove` or `item.canMove`. It will always return true. Since we passed `false` as `canMove` and that is not changing, the permission to move the item will not be updated.

We could fix this by not checking if the permission has changed and/or by checking the permission initially on mount.

I'll submit a PR with an initial mount solution.

**Comment by Ilaiwi** [comment]
released in 0.23.0
