### ISSUE TITLE
Google Calendar import anyone?

### ISSUE THREAD

**Issue by batchku** [namespace-ee/react-calendar-timeline#575]
**Is your feature request related to a problem? Please describe.**
Ability to generate timeline elements from multiple Google Calendars.

**Describe the solution you'd like**
Configuration files to provide API key and calendar ID, define color and formatting options.

**Describe alternatives you've considered**
Make my own.

**Additional context**
Has anyone here considered this?

**Comment by tobiasbueschel** [comment]
Thanks for creating this issue @batchku 🙏

Pulling this sort of data from Google's Calendar API can be easily achieved within your React application (here is an [example article that describes one approach](https://www.robinwieruch.de/react-fetching-data/)). Once you've fetched the data, you can ingest and render it with `react-calendar-timeline`.

I think that `react-calendar-timeline` should remain agnostic of the data source used and give the responsibility to the user, otherwise, this library will become unnecessarily loaded.

**Comment by Ilaiwi** [comment]
@tobiasbueschel thank you for answering this
