### ISSUE TITLE
onBoundsChange is called on every visibleTime[Start|End]

### ISSUE THREAD

**Issue by hckr** [namespace-ee/react-calendar-timeline#653]
**Describe the bug**

`onBoundsChange` is called on every `visibleTime[Start|End]` change and not only when it should.
The use of `react-redux` might be the reason, but I'm not sure why this happens.

**To Reproduce**

https://codesandbox.io/s/react-calendar-timeline-bug-timelines-linked-with-redux-u2mkb

**Expected behavior**

`onBoundsChange` is supposed to be called when "when the bounds in the calendar's canvas change" (as written in README)

**Screenshots**

![timeline-redux-bug](https://user-images.githubusercontent.com/1078650/65243126-030d9380-dae8-11e9-9e19-cc062d4872a5.gif)

**Library Version**
0.26.4

**Desktop:**
* OS: Linux
* Browser: Firefox
* Version 69.0

**Comment by Ilaiwi** [comment]
@hckr  I am not quite sure about this but I think `onBoundsChange` only applies when you use `defaultStartTime` and `defaultEndTime`

**Comment by hckr** [comment]
Do you mean that `onBoundsChange` shouldn't be used, when manually changing `visibleTimeStart`?

**Comment by Ilaiwi** [comment]
@hckr I think so but not quite sure. could you investigate it, please?

**Comment by hckr** [comment]
I don't understand what do you mean. How should I know if it should work that way or not? I'm not the author of the API. From my point of view, it shouldn't, as it might suggest the canvas is recreated on each scroll which probably is a performance issue. If it isn't recreated, then this event shouldn't fire, as canvas bounds don't change. And they shouldn't change on every scroll, that's why the lib uses a margin on left and right side of the visible area, right?

**Comment by Ilaiwi** [comment]
@hckr me neither I didn't write the API for the `boundaries change` so this needs to be a collaboration effort from both of us. I agree. This would cause huge performance issues if you are using vistableTime start/end.
The state management to achieve this would be a nightmare I would guess since here we are mixing controlled with uncontolled principles.
We scroll the calendar via scrollLeft property for the headers and the calendar you can read more about it [here](https://github.com/namespace-ee/react-calendar-timeline#behind-the-scenes)

**Comment by megasus** [comment]
So having had the same problem, I probably know the cause of this.
The onBoundsChange event will always fire when items or groups changed. Since your second connected timeline component does not have any items/groups props, a new instance of items and groups will be created whenever the store updates (visible time changes).

Even if your items/groups have the same values as before, the timeline will think they have changed as it's a new instance:
[Relevant code.](url)
This returns false: [{id: 1}] == [{id: 1}]

So to solve your problem: Make sure that items and groups are not initialized every time your component rerenders. Move them to state or store.

**Comment by hckr** [comment]
I don't understand. Items and groups never change, they are created only once in my example (App.jsx):

```
const { items, groups } = generateFakeData(3, 300);

const App = () => (
  <Provider store={store}>
    <ConnectedTimeline items={items} groups={groups} />
    <ConnectedTimeline />
  </Provider>
);

export default App;
```

**Comment by hckr** [comment]
Oh, ok. This is the root cause:
>Since your second connected timeline component does not have any items/groups props, a new instance of items and groups will be created whenever the store updates

**Comment by Ilaiwi** [comment]
@meengit thanks for the help
