### ISSUE TITLE
Is it possible to get full height for row even though not all items are seeing for the time?

### ISSUE THREAD

**Issue by dverkhovsky13** [namespace-ee/react-calendar-timeline#714]
When we have 2 items and set stackItems to true, so they'll be under each other, so there is no visual overlap when times collide that's great but when one of the items so far away that can't be seen from the first render the whole row does not expand (changes height). Is there some way to fix this?

**Comment by Ilaiwi** [comment]
@dverkhovsky13 this is not supported natively in the library. Although you can control the item height via the itemRenderer feature and [item prop renderer](https://github.com/namespace-ee/react-calendar-timeline#context) this is not recommended. Maybe when rowRenderer #673 feature hits production this can be controlled. For now, I am going to close this issue since We are not intending to support this soon. If you would like to contribute it to the source code though I would be happy to reopen it and help you in any capacity.
