### ISSUE TITLE
code style → Airbnb JavaScript Style Guide

### ISSUE THREAD

**Issue by signalwerk** [namespace-ee/react-calendar-timeline#90]
Airbnb JavaScript Style Guide is probably the most used eslint JavaScript code style. I would like to switch React Calendar Timeline to this style. What do you guys think. Would someone be willing to help to switch it? Since contributors are used to this code style I think it helps the community.

**Comment by mariusandra** [comment]
Hey, 

I find the [JavaScript Standard Style](https://standardjs.com/rules.html#javascript-standard-style), which this repository adheres to, quite used as well.

Personally I like it more than the [Airbnb guide](https://github.com/airbnb/javascript), as without semicolons it makes the code much more readable. [Insert long rant here about why semicolons make no sense in the age of build tools that add/remove them as needed to minimise the bundle size 😅]

So I'd keep it like this, at least for now.

One change that I would like to do, but have been stalling on because it would have invalidated many PRs and will cause issues with all the forks, is to rename the files from PascalCase to dash-case. So `src/lib/lines/HorizontalLines.js` would become `src/lib/lines/horizontal-lines.js` and `src/lib/items/Items.js` would become `src/lib/items/index.js`. I also find it more pleasing for the eye... but this is a minor thing... :)

**Comment by signalwerk** [comment]
Hmm... When I look at the Stars in Github I think Airbnb is way more popular (12k vs 53k). 

I think the naming of the files you brought up is fine. No strong opinion about that. 

Semicolons... Well I have an other opinion. But as you say: it's  an opinion and nobody is right or wrong. What would you say about that:

We take airbnb and overwrite the semicolon-rule? 

Since it's your repo I think it's only fair to take your Semicolon-Style.

**Comment by madisvain** [comment]
@signalwerk @mariusandra I know Airbnb is popular with their style but I also really like the style of JS Standard style. I would still propose to keep it - it's an opinion and I guess everybody has one :)

anyway react itself and some other really big libraries actually use it https://gist.github.com/feross/e0882df2fe673d6ce064

**Comment by signalwerk** [comment]
@madisvain @mariusandra all right. So we switch to JS Standard style and ditch `.eslintrc`. Right? Should we do that in a separate branch or change the test in master and do then the conversion? When would be good for you guys? I guess that will cause quite some changes? Did one of you tested it so far? Personally I think it would be good to do it in a branch so we can all work on it before we merge.

**Comment by mariusandra** [comment]
Hey, the JS Standard style is already implemented with `.eslintrc` with `"extends": "standard"` and `eslint-config-standard`. Nothing more to do here :).
